### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by GabiGunner** [manatails/uefiseven#16]
GenFvInternalLib.c:24:10: fatal error: uuid/uuid.h: No such file or directory
   24 | #include <uuid/uuid.h>
      |          ^~~~~~~~~~~~~

**Comment by enigma131** [comment]
I got same error.
How did you solve the missing include file ?
edit
Found error, uuid-dev packet was missing for compilation.

**Comment by GabiGunner** [comment]
> I got same error. How did you solve the missing include file ?

I just downloaded the compiled files.

**Comment by enigma131** [comment]
You don't compile the project ?
Manatails give no more response ...
