### ISSUE TITLE
point 7 of procedure

### ISSUE THREAD

**Issue by MrTatiTunes** [manatails/uefiseven#28]
Shall I rename the bootx64 from win 7 archive or copy it straight?
And what is EFI shell?
Sorry, I am really confused by English language strange precision...

7.Copy UefiSeven bootx64.efi to (HDD)\EFI\Microsoft\Boot\bootmgfw.efi using EFI shell

**Comment by MrTatiTunes** [comment]
IDK how to do it, as I can not get any access to UEFI partitions... I can browse to search for BCD with EasyBCD 2.4 prepare them or whatever I want, but no access as admin, system, trustedinstaller to those partitions (I have given them letters with diskpart before).

**Comment by acoul** [comment]
try to see if [this helps](https://github.com/manatails/uefiseven/issues/9) you. You can perhaps find some further info over at  [mydigitallife thread](https://forums.mydigitallife.net/threads/uefiseven-easily-boot-windows-7-on-uefi-class-3-devices.82137/page-22#post-1791373) 

on your Win7 installed disk you do the following:

- Rename bootmgfw.efi at (HDD)\EFI\Microsoft\Boot\ to bootmgfw.original.efi
- Copy UefiSeven bootx64.efi to (HDD)\EFI\Microsoft\Boot\bootmgfw.efi

**Comment by MrTatiTunes** [comment]
> 

Nice, thank you for so quick response... still the instruction is not really leading to the point, which HDD!!!? I wrote already that small UEFI Boot No letter Partitions are not accessible in any way. I am starting to think it is on the system partition... It is all crazy stuff as all instructions I read recently work like this https://www.youtube.com/watch?v=QvET1-e3aJI&list=PLfxdoKg8EsqYG_v9-zfvt1pbbJaxq94Vw&index=11  
I am not stupid, but the level of preciseness in communication offered by the English language is unsatisfactory maybe this together with so broad popularity of these languages (as native English speakers say, it changes to different dialect every 30 miles) is the cause of contemporary world problems. :)

Still don't know what is EFI Shell ...

**Comment by acoul** [comment]
you may check & familiarize your self with the [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition) or here [EFI System Partition](https://wiki.osdev.org/EFI_System_Partition)

& you can use a [linux flash/usb key](https://www.system-rescue.org/Download/) to easily work on this partition

I am sure there is a [windows way](https://github.com/wictorChaves/CatalinaInstallVostro5470/blob/master/mount-efi-windows.md) to do this too.

instead of EasyBCD, try [BootIce](https://www.majorgeeks.com/files/details/bootice_64_bit.html). more info [here](https://reboot.pro/index.php?showtopic=21508)

**Comment by MrTatiTunes** [comment]
> you may check & familiarize your self with the [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition) or here [EFI System Partition](https://wiki.osdev.org/EFI_System_Partition)
> 
> & you can use a [linux flash/usb key](https://www.system-rescue.org/Download/) to easily work on this partition
> 
> I am sure there is a [windows way](https://github.com/wictorChaves/CatalinaInstallVostro5470/blob/master/mount-efi-windows.md) to do this too.
> 
> instead of EasyBCD, try [BootIce](https://www.majorgeeks.com/files/details/bootice_64_bit.html). more info [here](https://reboot.pro/index.php?showtopic=21508)

Nice Definitively will give a try :)
this come out of proffessional mode:
![obraz](https://github.com/manatails/uefiseven/assets/30302908/d5959d48-d574-477c-a693-c4f569b50148)

**Comment by MrTatiTunes** [comment]
This is on Compatibility mode, will check on UEFI mode later, how much will to complicate world represent those ppl who design such weird parts of codes for MS and other systems... what is the purpose of that? Some codes are like people talking uninterruptible and without possibility to stop them without gunshot...

**Comment by MrTatiTunes** [comment]
> you may check & familiarize your self with the [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition) or here [EFI System Partition](https://wiki.osdev.org/EFI_System_Partition)
> 
> & you can use a [linux flash/usb key](https://www.system-rescue.org/Download/) to easily work on this partition
> 
> I am sure there is a [windows way](https://github.com/wictorChaves/CatalinaInstallVostro5470/blob/master/mount-efi-windows.md) to do this too.
> 
> instead of EasyBCD, try [BootIce](https://www.majorgeeks.com/files/details/bootice_64_bit.html). more info [here](https://reboot.pro/index.php?showtopic=21508)

Thanks, I am getting more and more frustrated on this shi**** searching some more BCD and can not find the one it comes here as first... and has completely no real link to anywhere...
 This block (of concrete) who designed and accepted verified and certified this System is someone I would love to shoot at... why there is nothing like one place where UEFI data is placed, and where it is, if BIOS now is not involved in start, so where is the list of the systems to chose for boot? I get 3 screens of choices... WTF?

**Comment by MrTatiTunes** [comment]
> you may check & familiarize your self with the [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition) or here [EFI System Partition](https://wiki.osdev.org/EFI_System_Partition)
> 
> & you can use a [linux flash/usb key](https://www.system-rescue.org/Download/) to easily work on this partition
> 
> I am sure there is a [windows way](https://github.com/wictorChaves/CatalinaInstallVostro5470/blob/master/mount-efi-windows.md) to do this too.
> 
> instead of EasyBCD, try [BootIce](https://www.majorgeeks.com/files/details/bootice_64_bit.html). more info [here](https://reboot.pro/index.php?showtopic=21508)

Thanks, I am getting more and more frustrated on this shi**** searching some more BCD and can not find the one it comes here as first... and has completely no real link to anywhere...
 This block (of concrete) who designed and accepted verified and certified this System is someone I would love to shoot at... why there is nothing like one place where UEFI data is placed, and where it is, if BIOS now is not involved in start, so where is the list of the systems to chose for boot? I get 3 screens of choices... WTF? Here is how it looks like:
https://youtu.be/zKA_cRkyosM

**Comment by acoul** [comment]
glad you make progress & dig further into this

> ...  is someone I would love to shoot at... 

personally I find poems to have far more devastating effect & fruitful results :)

open source is a form of poetry, especially when they inspire others to do the same

cheers
