### ISSUE TITLE
It stucks at Starting Windows without even a Logo

### ISSUE THREAD

**Issue by caroexe** [manatails/uefiseven#5]
I did everything like in the instructions but when i try to install windows i get stuck at Starting Windows and like i said the Windows 7 logo doesn't even show up. Tried another USB stick and ISO but it didn't worked.

![WhatsApp Image 2021-03-25 at 18 36 34 (1)](https://user-images.githubusercontent.com/45734648/112500113-25e1cd80-8d99-11eb-81fe-c2b517c93a21.jpeg)

![WhatsApp Image 2021-03-25 at 18 35 45](https://user-images.githubusercontent.com/45734648/112500163-3134f900-8d99-11eb-9153-92d51a24111d.jpeg)

**Comment by MrHallway0** [comment]
I am getting about as far as you, just you can see the start of the logo forming... where you ever able to fix it?

**Comment by XMidasXX** [comment]
I have the same problem and idk where to place the ini file
