### ISSUE TITLE
Live Windows 7 system

### ISSUE THREAD

**Issue by acoul** [manatails/uefiseven#9]
Greetings,

can uefiseven be installed on a live (pre-installed) system ?

best regards

**Comment by SamJoex** [comment]
Yea. But instead of starting at Step 1, you'll start at Step 6. Steps 1 through 5 are applicable only for installing Windows.

**Comment by acoul** [comment]
I did step 6 and the uefi boot hangs on the windows 7 boot logo. I am able to arping & vnc to this system from another workstation, but the screen is black with a stuck mouse cursor in the middle. Pressing the power button, does shutdown the system properly. This is on an [ASRock J4125-ITX](J4125-ITX) motherboard.

On safe mode, right after CLASSPNP.SYS it gets stuck on asstore64.sys. Pressing the power button, also shuts down the system properly.

**Comment by acoul** [comment]
I followed again the instructions step 6 & 7 and everything worked like a charm.

thank you for the feedback

**Comment by acoul** [comment]
just to bring a follow-up. I tested uefiseven on my [ASRock J4125-ITX](https://github.com/manatails/uefiseven/issues/J4125-ITX) system today again with success. it also uefi only boots just fine on my latitude 5280.

it doesn't succeed though on my Gigabyte A320-H with either a Radeon HD 8490 nor Nvidia GTX-1050 GPU. the system though is alive, keyboard works, num lock responds and when power button is pressed, systems shuts down normally, but no display output.

same on my GIGABYTE GB-BRR3H-4300 BRIX system, though it hangs (probably due to lack of proper drivers). Safe mode does display text before it hangs

I am getting some j4105 BRIX for the office and I am happy to run Windows 7 as some applications we use are not happy with Windows 10

**Edit**: J4105 BRIX works well with uefiseven
